# Generated by Django 4.1.1 on 2022-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200, unique=True)),
                ('ciNit', models.CharField(max_length=10, unique=True)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
    ]
