# Generated by Django 4.1.1 on 2022-10-07 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_address_packet_receiver_service_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_admin_superUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
